graph LR
    A[Home] --> B[Books] --> C[Book]
    A[Home] --> D[Categories] --> B[Books Filtered / All] --> C[Book]
    A[Home] --> C[Book]
    A[Home] --> E[Events]
    A[Home] --> G[About Us]
    A[Home] --> H[Donate]
    I[Search] --> B[Books Filtered / All] --> C[Book]
    A[Home] --> J[Login]
    J[Login] --> K[Register]
    J[Login] --> A[Home]
    K[Register] --> A[Home]
